services:
  backend:
    build: ./backend
    command: ["fastapi", "dev", "app/main.py", "--host", "0.0.0.0", "--port", "8000"]
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app/app

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    environment:
      API_PROXY_TARGET: http://backend:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
